define([], function () {
  return {
    PropertyPaneDescription: "Description",
    BasicGroupName: "Basic Settings",
    AdvancedGroupName: "Advanced Settings",
    SeeMoreSettingGroupName: "See More Settings",
    ListNameFieldLabel: "List",
    ViewTypeFieldLabel: "View Type",
    DescriptionFieldLabel: "Title",
    TitlePositionFieldLabel: "Webpart Title Position",
    ColumnFieldLabel: "Number Of Columns",
    viewTypeStyle1: "Square",
    viewTypeStyle2: "Circle",
    // viewTypeStyle3: "Style 3",
    // viewTypeStyle4: "Style 4",
    LeftFieldLabel: "Left",
    CenterFieldLabel: "Center",
    RightFieldLabel: "Right",
    Column1FieldLabel: "1 Column",
    Column2FieldLabel: "2 Column",
    Column3FieldLabel: "3 Column",
    Column4FieldLabel: "4 Column",
    ReadMoreFieldLabel: "Read More",
    SeparatorFieldLabel: "Separator",
    EnableFieldLabel: "On",
    NoEnableFieldLabel: "Off",
    LeftFieldLabel: "Left",
    RightFieldLabel: "Right",
    BottomFieldLabel: "Botton",
    OverlayFieldLabel: "Overlay",
    OverlayWithTransFieldLabel: "Overlay with Transparent",
    TextPositionFieldLabel: "Text Position",
    SeeMoreSettingEnableTextFieldLable: "See More Enable",
    EnableSeeMoreTextFieldLable: "On",
    NoSeeMoreTextFieldLable: "Off",
    SeeMoreTextFieldLable: "Text",
    NoOfItemsFieldLable: "Number Of Items",
    SeeMoreLinkUrlFieldLable: "See More Link",
    CategoryFieldLabel: "Category",
    CreateListGroupName: "Create List",
    CreateListNameFieldLabel: "List Name",
    CreateButtonNameFieldLabel: "Create",
    GoToTextFieldLabel: "Go To",
    OverlayTransparentFieldLabel: "Overlay Transparent",
  };
});
