define([], function () {
  return {
    PropertyPaneDescription: "Description",
    BasicGroupName: "Basic Settings",
    AdvancedGroupName: "Advanced Settings",
    ListNameFieldLabel: "List",
    TextPositionFieldLabel: "Banner Text Position",
    ImagePositionFieldLabel: "Image Position",
    SpeedFieldLabel: "Slide Interval (in sec)",
    TextSizeFieldLabel: "Font Size",
    HeightFieldLable: "Banner Height",
    DotsFieldLabel: "Dots Navigation",
    ArrowsFiledLabel: "Arrow Navigation",
    AutoPlayFieldLabel: "Auto Play",
    slideViewFieldLabel: "View Type",
    slideDetailPositionFieldLable: "Slide Detail Position",
    slideTitleFromListFieldLabel: "Slide Title From List",
    displayFromListFieldLabel: "To be display from list",
    noDisplayFromListFieldLabel: "Not to be display from list",
    dispalyFieldLabel: "On",
    noDisplayFieldLabel: "Off",
    enableFieldLabel: "On",
    noEnableFieldLabel: "Off",
    slideViewBasicFieldLabel: "Basic",
    slideViewBasicDetailFieldLabel: "Basic With Detail",
    slideViewDetailFieldLabel: "Slide With Detail",
    bottomLeftFieldLabel: "Bottom Left",
    topLeftFieldLabel: "Top Left",
    topRightFieldLabel: "Top Right",
    bottomRightFieldLabel: "Bottom Right",
    arrowsOnMouseOverFieldLabel: "Arrow On Mouse Over",
    CategoryFieldLabel: "Category",
    CreateListGroupName: "Create List",
    CreateListNameFieldLabel: "List Name",
    CreateButtonNameFieldLabel: "Create",
    GoToTextFieldLabel: "Go To",
    topLeftImagePosFieldLable: "Top Left",
    topCenterImagePosFieldLable: "Top Center",
    topRightImagePosFieldLable: "Top Right",
    rightCenterImagePosFieldLable: "Right Center",
    bottomRightImagePosFieldLable: "Bottom Right",
    bottomCenterImagePosFieldLable: "Bottom Center",
    bottomLeftImagePosFieldLable: "Bottom Left",
    leftCenterImagePosFieldLable: "Left Center",
    centerImagePosFieldLable: "Center",
  };
});
