define([], function () {
  return {
    PropertyPaneDescription: "Description",
    BasicGroupName: "Basic Settings",
    AdvancedGroupName: "Advanced Settings",
    SeeMoreSettingGroupName: "See More Settings",
    DescriptionFieldLabel: "Title",
    ListNameFieldLabel: "List",
    TitlePositionFieldLabel: "Webpart Title Position",
    ColumnsFieldLabel: "Number Of Columns",
    RoundedCorner: "Round Corner",
    isRegionDisplayLabel: "Region Display",
    ViewTypeFieldLabel: "View Type",
    SpeedFieldLabel: "Slide Interval (in sec)",
    DotsFieldLabel: "Dots Navigation",
    ArrowsFiledLabel: "Arrow Navigation",
    AutoPlayFieldLabel: "Auto Play",
    slideToShowFiledLabel: "Slides To Show",
    slideToScrollFieldLabel: "Slides To Scroll",
    dispalyFieldLabel: "On",
    noDisplayFieldLabel: "Off",
    enableFieldLabel: "On",
    noEnableFieldLabel: "Off",
    roundCornerFieldLabel: "To be round corner",
    noRoundCornerFieldLabel: "Not to be round corner",
    regionDisplayFieldLabel: "To be region display",
    noRegionDisplayFieldLabel: "Not to be region display",
    viewTypeSliderFieldLabel: "Slider",
    viewTypeBasicFieldLabel: "Basic",
    viewTypeBlockFieldLabel: "Block",
    LeftFieldLabel: "Left",
    CenterFieldLabel: "Center",
    RightFieldLabel: "Right",
    arrowsOnMouseOverFieldLabel: "Arrow On Mouse Over",
    SeeMoreSettingEnableTextFieldLable: "See More Enable",
    EnableSeeMoreTextFieldLable: "On",
    NoSeeMoreTextFieldLable: "Off",
    SeeMoreTextFieldLable: "Text",
    NoOfItemsFieldLable: "Number Of Items",
    SeeMoreLinkUrlFieldLable: "See More Link",
    CategoryFieldLabel: "Category",
    CreateListGroupName: "Create List",
    CreateListNameFieldLabel: "List Name",
    CreateButtonNameFieldLabel: "Create",
    GoToTextFieldLabel: "Go To",
  };
});
